export const GET_DATA_PRODUCTS = 'GET_DATA_PRODUCTS';
export const START_GET_DATA_PRODUCTS = 'START_GET_DATA_PRODUCTS';
export const END_GET_DATA_PRODUCTS = 'END_GET_DATA_PRODUCTS';
export const GET_DATA_PRODUCTS_SUCCESS = 'GET_DATA_PRODUCTS_SUCCESS';
export const GET_DATA_PRODUCTS_FAIL = 'GET_DATA_PRODUCT_FAIL';